markdown: kramdown

collections:
  chapters:
    order:
      - b.md
      - a.md

kramdown:
  # fenced code blocks
  input: GFM
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    css_class: 'highlight'
